### ISSUE TITLE
Create Unit of Measurement in Admin Module

### ISSUE THREAD

**Issue by pembertonc** [pembertonc/NAITS#9]
Create the interface component in the Admin Module to add different types of Units of measurement to the system.  This interface will go into the Admin module.  it should allow the user to list all Units of Measurement,  filter the units of measurement by categories,  that is volume,  length weight.   and so on.
The user must be able to add, delete, edit units of measurement.

**Comment by vashanti** [comment]
What would represent categories in the Unit of Measurement? If a user creates a new unit of measurement, there is no field to specify what type of unit it is (category)

**Comment by pembertonc** [comment]
The category is essentially the grouping that the unit falls under.  so gallons (US) falls under volume while feet fall under length or distance.  minutes under time and so on.

**Comment by vashanti** [comment]
How is that represented? BaseUnit?

**Comment by pembertonc** [comment]
The baseUnit field holds an instance of UnitOfMeasurement.  so for cm, km, dm etc m will be the base unit instance.
